
---
deployment:
 tasks:
 - export DEPLOYPATH=	/home/canoearc/repositories/html-ccc-js-personalwebsite
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp style.css $DEPLOYPATH
 - /bin/cp mediaqueries.css $DEPLOYPATH
 - /bin/cp script.js $DEPLOYPATH
 - /bin/cp -R assets $DEPLOYPATH